export const NotificationType = {
   ORDER_PLACED: 'ORDER_PLACED',
   ORDER_SHIPPED: 'ORDER_SHIPPED',
   ORDER_DELIVERED: 'ORDER_DELIVERED',
   ORDER_CANCELLED: 'ORDER_CANCELLED',
   ORDER_RECEIVED: 'ORDER_RECEIVED',
   ORDER_DONE: 'ORDER_DONE',

   PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
   PAYMENT_FAILED: 'PAYMENT_FAILED',

   PROMOTIONAL_OFFER: 'PROMOTIONAL_OFFER',
   NEW_PRODUCT_AVAILABLE: 'NEW_PRODUCT_AVAILABLE',

   ACCOUNT_ACTIVATED: 'ACCOUNT_ACTIVATED',
   PASSWORD_RESET: 'PASSWORD_RESET',

   SHIPMENT_BOOKED: 'SHIPMENT_BOOKED',
   SHIPMENT_DELAYED: 'SHIPMENT_DELAYED',
   SHIPMENT_OUT_FOR_DELIVERY: 'SHIPMENT_OUT_FOR_DELIVERY',
   SHIPMENT_DELIVERY_FAILED: 'SHIPMENT_DELIVERY_FAILED',
   SHIPMENT_DELIVERED: 'SHIPMENT_DELIVERED',
};
